### ISSUE TITLE
Running on ESP8266

### ISSUE THREAD

**Issue by do-gooder** [kr0ner/OneESP32ToRuleThemAll#48]
How can I run your project on ESP8266?

[logs_esp32-poe-technik_compile.txt](https://github.com/user-attachments/files/17689205/logs_esp32-poe-technik_compile.txt)

My config:
```
esphome:
  name: esp32-poe-technik
  friendly_name: ESP32-PoE Technik
  platformio_options:
    build_flags:
      - "-std=gnu++17"
    build_unflags:
      - "-std=gnu++11"
      - "-fno-rtti"

esp8266:
  board: nodemcuv2
  # framework:
    # type: arduino

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "XXX"

ota:
  platform: esphome
  password: "XXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Heatingpump-Esp8266"
    password: "XXX"

time:
  - platform: homeassistant
    id: homeassistant_time

substitutions:
  interval_very_fast: 15s
  interval_fast: 30s
  interval_medium: 60s
  interval_slow: 5min
  interval_very_slow: 15min
  interval_once_in_a_while: 1h

  entity_room_temperature: "sensor.durchschnittstemperatur_haus_ohne_keller"
  entity_humidity: "sensor.durchschnitt_luftfeuchtigkeit_haus"

#########################################
#                                       #
#   SPI configuration                   #
#                                       #
#########################################
spi:
  id: McpSpi
  clk_pin: D5
  mosi_pin: D7
  miso_pin: D6

#########################################
#                                       #
#   CAN configuration                   #
#                                       #
#########################################
canbus:
  - id: !extend wp_can
    platform: mcp2515
    spi_id: McpSpi
    cs_pin: D2

#########################################
#                                       #
#   Buttons                             #
#                                       #
#########################################
button:
  - platform: restart
    name: "Restart ESP32-PoE Technik"

#########################################
#                                       #
#   Ethernet Konfiguration              #
#                                       #
#########################################
#ethernet:
#  type: LAN8720
#  mdc_pin: GPIO23
#  mdio_pin: GPIO18
#  clk_mode: GPIO0_OUT
#  phy_addr: 0
#  power_pin: GPIO12

#########################################
#                                       #
#   Packages                            #
#                                       #
#########################################
packages:
# energymeter: !include yaml/energymeter.yaml
# watermeter: !include yaml/watermeter.yaml
# sensors: !include yaml/sensors.yaml
# thz404: !include yaml/thz404.yaml
# thz504: !include yaml/thz504.yaml
# thz55eco: !include yaml/thz5_5_eco.yaml
  ttf07: !include yaml/ttf07.yaml
# kondensatpumpe: !include yaml/kondensatpumpe.yaml

#########################################
#                                       #
#   EVU Sperre                          #
#                                       #
#########################################
#switch:
#  - platform: gpio
#    name: "EVU Sperre"
#    id: evu_sperre
#    pin: GPIO5

```
