### ISSUE TITLE
Can't get any data with canbus: platform: esp32_can

### ISSUE THREAD

**Issue by giggo** [kr0ner/OneESP32ToRuleThemAll#52]
I am using an ESP32-S3-Devkitc-1

```
esphome:
  name: waermepumpe
  friendly_name: "Wärmepumpe CAN Interface"
  platformio_options:
    build_flags:
      - "-std=gnu++17"
    build_unflags:
      - "-std=gnu++11"
      - "-fno-rtti"

  platform: esp32
  board: esp32-s3-devkitc-1

```
I had to remove the SPI definition and modify the Canbus Config like this

```
canbus:
  - platform: esp32_can
    # TODO: Rename id
    id: !extend wp_can
    tx_pin: GPIO5
    rx_pin: GPIO4
    #can_id: 680
    use_extended_id: false
    bit_rate: 20kbps
```

This is a canbus config that worked for me with robertreiter's code but I can't received any data from my Stiebel Eltron WPL18 heatpump. DEBUG is enabled. 
I just get this:

```
...
[00:54:14][D][canbus:035]: send standard id=0x6a2 rtr=FALSE size=7
[00:54:14][D][canbus:035]: send standard id=0x6a2 rtr=FALSE size=7
[00:54:14][D][canbus:035]: send standard id=0x6a2 rtr=FALSE size=7
...

```
Any idea?
